- name: Check registered variable for emptiness
  hosts: localhost

  vars:
    foo: power
  tasks:
 
    - debug: msg="I've got a '{{ foo }}' and am not afraid to use it!"
      when: foo is defined

    - fail: msg="Bailing out. this play requires 'bar'"
      when: bar is undefined

