- name: Looping over Integer Sequences Example 
  hosts: localhost

  tasks:
    - name: Print even numbers from 0 to 10 in format "number-X"
      debug: msg="{{ item }}"
      with_sequence: start=0 end=16 stride=2 format=number-%d

    - name: Print numbers from 1 to 3
      debug: msg="{{ item }}"
      with_sequence: count=3
