Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "day1.ansible.cdp"
  config.vm.network :private_network, ip: "192.168.56.21"

  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    # Virtual Machine Name
    vb.name = "ansible-day-1"
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
    yum install -y epel-release
    yum install -y python-pip
    pip install -U pip
    pip install -U ansible
  SHELL
end